version: "3.7"
services:
  db:
    image: postgres:12.2
    container_name: telecom_db
    volumes:
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./logs:/logs
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: initial
    command: -c config_file=/etc/postgresql/postgresql.conf -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c log_statement=all

  migrate:
    image: flyway/flyway:6.2.4
    container_name: migrate_db
    volumes:
      - ./conf/flyway.conf:/flyway/conf/flyway.conf
      - ./migration:/flyway/db/migration
      - ./scripts/wait-for-it.sh:/usr/bin/wait-for-it.sh
    entrypoint: ["wait-for-it.sh", "db:5432", "--strict", "--timeout=60", "--", "/flyway/flyway", "migrate"]
    depends_on:
      - db